image: node:latest

cache:
  paths:
    - node_modules/

build:
  script:
    - npm install
    - npm run build
  artifacts:
    name: "coverage-$CI_COMMIT_SHORT_SHA"
    paths:
      - build/
    expire_in: 30 days
