name: Website CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build for Production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
        
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules
        
    - name: npm install and build
      run: |
        npm install
        npm run build --if-present

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
        
