name: Website CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build for Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules

      - name: npm install and build
        env:
          REACT_APP_MAILCHIMP_URL: ${{ secrets.REACT_APP_MAILCHIMP_URL }}
          REACT_APP_MAILCHIMP_U: ${{ secrets.REACT_APP_MAILCHIMP_U }}
          REACT_APP_MAILCHIMP_ID: ${{ secrets.REACT_APP_MAILCHIMP_ID }}
        run: |
          npm install
          npm run build --if-present

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
